name: deploy2dockerhub
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      -
        name: Show version number
        run: echo "Version is ${{ steps.package-version.outputs.current-version }}"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: simplycoders/dockerql:latest,simplycoders/dockerql:${{ steps.package-version.outputs.current-version }}